### ISSUE TITLE
Stuck whit value's

### ISSUE THREAD

**Issue by SniperVegeta** [dtjohnson/xlsx-populate#39]
Hello,

im stuck at getting my values out of an template

i got an xlsx whit on A5 an ID<num> and what to get the B5 C5 etc value's of that row and store them in an array ( im using nodejs)

```
var XlsxPopulate = require('xlsx-populate');
		csv.parseCSV("./csv/"+file, function(data){ //here i parse an csv and read the 1st data
		XlsxPopulate.fromFileAsync("./Klanten.xlsx") // here A5 got my ID<num>
			.then(workbook => {
				for (i = 0; i < data.length; i++) {
					//console.log(data[i].Account);
					var ddata = workbook.find("ID"+data[i].Account);
					console.log(ddata);
					//console.log(ddata[0]._ref.columnName); // whit 1.5.5 this works with 1.6.0 it fails
					//console.log(ddata[0]._ref.rowNumber);// whit 1.5.5 this works with 1.6.0 it fails
					//console.log(ddata[0]._ref.columnName +''+ ddata[0]._ref.rowNumber);
					const testdata = workbook.sheet(0).cell("A5").value();
					//var testdata = workbook.sheet(0).cell('A5').value();
					console.log(testdata);
				}
			});
		});
```

in 1.5.5 ddata =

[ Cell {
    _row: Row { _sheet: [Object], _node: [Object], _cells: [Object] },
    _node: { name: 'c', attributes: [Object], children: [Object] },
    _ref:
     { type: 'cell',
       columnAnchored: false,
       columnName: 'A',
       columnNumber: 1,
       rowAnchored: false,
       rowNumber: 5 } } ]

in 1.6.0 ddata = 
[ Cell {
    _row: Row { _sheet: [Object], _node: [Object], _cells: [Object] },
    _columnNumber: 1,
    _value: 'undefined' } ]

but in both sanario's (1.5.5 and 1.6.0)
testdata = undefined

am i doing someting wrong?

hope to hear from you

**Comment by dtjohnson** [comment]
You should read the [API docs](https://github.com/dtjohnson/xlsx-populate#api-reference). You were using an undocumented private property `_ref` of the Cell. Undocumented properties/methods could change at any time (especially private ones).

You can get the cell row number and column name the proper way with the [Cell.rowNumber](https://github.com/dtjohnson/xlsx-populate#Cell+rowNumber) and [Cell.columnName](https://github.com/dtjohnson/xlsx-populate#Cell+columnName) methods. You can also use the [Cell.relativeCell](https://github.com/dtjohnson/xlsx-populate#Cell+relativeCell) method to grab a cell relative to the one you found.

**Comment by SniperVegeta** [comment]
Hi dtjohnson,

thanks for your fast replay,
yes i read the API etc, but i ddont get that part

Maybe im from examples,

but be4 i use the privat things
i tryed ( as doc ): 

const testdata = workbook.sheet(0).cell("A5").value();
sould get me the data in cell A5, but it doesnot. its always undefined

how should i use the Cell.rowNumber etc?
i tryed alot with it but somehow always get someting like:

```
(node:3560) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: cell is not defined
(node:3560) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Hope to hear from you ( whit an example how to use it )

Thanks in advance.

**Comment by dtjohnson** [comment]
If your cell is empty then `cell.value()` will return `undefined`.

The other methods are straightforward:
```js
// Get a cell
workbook.sheet(0).cell("A5");

// Get the cell's row number
const rowNumber = cell.rowNumber();

// Get the cells column name
const columnName = cell.columnName();

// Get a cell 1 row down and 2 columns to the right
const otherCell = cell.relativeCell(1, 2);
```

**Comment by SniperVegeta** [comment]
Still dont get it.
as in 1.5.5

```
var ddata = workbook.find("ID"+data[i].Account);
console.log(ddata);
```

Console.log =
```
[ Cell {
    _row: Row { _sheet: [Object], _node: [Object], _cells: [Object] },
    _node: { name: 'c', attributes: [Object], children: [Object] },
    _ref:
     { type: 'cell',
       columnAnchored: false,
       columnName: 'A',
       columnNumber: 1,
       rowAnchored: false,
       rowNumber: 5 } } ]
```
So it knows A5 got my data, as it can find the cell
but 

`const testdata = workbook.sheet(0).cell('A5').value();` is `undefined`

`console.log(ddata.rowNumber);`
outputs `undefined`
`console.log(ddata.value());` gives the error as below

so im doing:
`const cell = workbook.sheet(0).cell(workbook.find("ID"+data[i].Account));`
what gives error
so rewrite:

```
var celldata = ddata[0]._ref.columnName +''+ ddata[0]._ref.rowNumber; // But this may not
const cell = workbook.sheet(0).cell(celldata);
console.log(cell.columnName());
console.log(cell.rowNumber());
console.log(cell.value());
```
gives me:
```
A
5
(node:16560) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: conssole is not defined
(node:16560) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```


ill upgrade to 1.6.0 and try your style again, ill update later on.

**Comment by SniperVegeta** [comment]
1.6.0

```
var ddata = workbook.find("ID"+data[i].Account);
console.log(ddata);
```

Console.log:
```
[ Cell {
    _row: Row { _sheet: [Object], _node: [Object], _cells: [Object] },
    _columnNumber: 1,
    _value: 'undefined' } ]
```

So it cannot find my cell?

```
var testdata = workbook.sheet(0).cell('A5').value;
console.log(testdata);
```
log = `undefined`

Hope to hear from you

**Comment by dtjohnson** [comment]
Does your workbook have more than one sheet? Perhaps `find` is returning a match in a different sheet than the 1st sheet.

**Comment by SniperVegeta** [comment]
nope 1 sheet only

edit whit 1.5.5

seems like after the find:
it can:
```
cell.relativeCell(0, 1).value();
cell.relativeCell(0, 2).value();
```
all outputs are correct.

but at 1.6.0 it all turns `undefined`

it looks like after find in 1.5.5 its "empty" ( like its replaced whit nothing )
in 1.6.0 the find not working at all.

hope to hear from you

**Comment by dtjohnson** [comment]
Ah. I see the issue now. I'll get a fix out.

**Comment by dtjohnson** [comment]
OK. I just published v1.6.1 that should fix the issue.

**Comment by SniperVegeta** [comment]
the find is working in 1.6.1 and its not empty after find

i get:
```
[ Cell {
    _row: Row { _sheet: [Object], _node: [Object], _cells: [Object] },
    _columnNumber: 1,
    _styleId: 1,
    _value: 'ID100464' } ]
```
what is value correct
but how can i get the active cell in
`cell.relativeCell(0, 1).value();`
again i can get the `console.log(ddata[0]._columnNumber)` but the rowNumber is missing.
but i guess this are privat props again.
i cant get the `ddata.colmnNumber()`
i get error:
`(node:13668) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: ddata[0].colmnNumber is not a function`

Snipet in 1.5.5 worked whit the privats props
```
var ddata = workbook.find("ID"+data[i].Account);
var celldata = ddata[0]._ref.columnName +''+ ddata[0]._ref.rowNumber;
var cell = workbook.sheet(0).cell(celldata);
console.log(cell.columnNumber());
console.log(cell.rowNumber());
somevar1 = cell.relativeCell(0, 1).value();
somevar2 = cell.relativeCell(0, 2).value();
// etc etc
```

in 1.6.1 i cant get the var cell for `cell.relativeCell(x, x).value();`

btw wow that u release fast 👍

**Comment by SniperVegeta** [comment]
humm got more results now,
dunno why, but somehow it works now 

i get now:

```
Cell {
  _row:
   Row {
     _sheet:
      Sheet {
        _workbook: [Object],
        _idNode: [Object],
        _node: [Object],
        _maxSharedFormulaId: -1,
        _mergeCells: {},
        _hyperlinks: {},
        _relationships: [Object],
        _rows: [Object],
        _sheetDataNode: [Object],
        _columns: [],
        _colsNode: [Object],
        _colNodes: [Object],
        _sheetPrNode: [Object],
        _mergeCellsNode: [Object],
        _hyperlinksNode: [Object] },
     _node: { name: 'row', attributes: [Object], children: [Object] },
     _cells:
      [ ,
        [Circular],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  _columnNumber: 1,
  _styleId: 1,
  _value: 'ID100464' }
```

and on 
`console.log(ddata[0].columnName());` = `A`
`console.log(ddata[0].rowNumber());` = `6`

so my 
```
var celldata = ddata[0].columnName() +''+ ddata[0].rowNumber();
var cell = workbook.sheet(0).cell(celldata);
```
is correct and thus:
`cell.relativeCell(0, 2).value();` are correct to :)

to be sure ill uninstall and install again and will let you know / close this if correct 👍

**Comment by SniperVegeta** [comment]
and its all correct.

thanks again for the fast replay 👍
